# Generated by Django 3.2.11 on 2022-01-14 16:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220114_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
