# Generated by Django 3.2.11 on 2022-01-14 17:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
